#pragma once
#include <wtypes.h>
#include <windef.h>
#include <SFML/Graphics.hpp>
#include <SFML\System.hpp>
#include <SFML\Audio.hpp>
#include <stdio.h>
#include <Box2D\Box2D.h>
#include <sfeMovie\Movie.hpp>
#define _CRT_SECURE_NO_WARNINGS
#include <sfeMovie\Visibility.hpp>
#include <io.h>
#include <iostream>
#include <fstream>
#include <iomanip>
#include <cstddef>
#include <stdlib.h>
#include <boost\archive\binary_iarchive.hpp>
#include <boost\archive\binary_oarchive.hpp>
#include <boost\archive\xml_iarchive.hpp>
#include <boost\archive\xml_oarchive.hpp>
#include <boost\archive\text_iarchive.hpp>
#include <boost\archive\text_oarchive.hpp>
#include <boost\serialization\list.hpp>
#include <boost\serialization\base_object.hpp>
#include <boost\serialization\utility.hpp>
#include <boost\serialization\assume_abstract.hpp>
#include <boost\serialization\wrapper.hpp>
#include <boost\serialization\string.hpp>
#include <boost\serialization\serialization.hpp>
#include <boost\serialization\array.hpp>
#include <fstream>
#include <WinBase.h>
#include <list>
#include <thread>
#include <string>
